# Generated by Django 3.0.2 on 2020-01-13 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectMPR', '0001_initial'),
    ]

    operations = [
    ]
